### ISSUE TITLE
why airixss suddenly stop with scanning big txt file?

### ISSUE THREAD

**Issue by superawesometv** [ferreiraklet/airixss#1]

**Comment by ferreiraklet** [comment]
Please, if  you are able to, contact me at discord - ferreira#9313

**Comment by superawesometv** [comment]
Added thx

Il gio 7 apr 2022, 4:54 PM ferreiraklet ***@***.***> ha
scritto:

**Comment by sp1nn4k3r** [comment]
Added thx
