### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by Kalimon12** [ferreiraklet/airixss#2]
airixss.go:14:9: no required module provides package github.com/chromedp/cdproto/page: go.mod file not found in current directory or any parent directory; see 'go help modules'                                                                                                
airixss.go:15:9: no required module provides package github.com/chromedp/chromedp: go.mod file not found in current directory or any parent directory; see 'go help modules'

**Comment by abramas** [comment]
cat sqli-time.txt | Jeeves --payload-time 5

**Comment by ferreiraklet** [comment]
Try installing chromedp with go command
`go install github.com/chromedp/chromedp@latest`
