### ISSUE TITLE
Error in installing "is a program, not an importable package"

### ISSUE THREAD

**Issue by hellofresh01** [ferreiraklet/airixss#4]
I am getting this error while installing

λ go build
go: finding module for package github.com/chromedp/cdproto/page
go: finding module for package github.com/chromedp/chromedp
go: downloading github.com/chromedp/chromedp v0.8.1
go: downloading github.com/chromedp/cdproto v0.0.0-20220428002153-285dfb42699c
go: found github.com/chromedp/cdproto/page in github.com/chromedp/cdproto v0.0.0-20220428002153-285dfb42699c
go: found github.com/chromedp/chromedp in github.com/chromedp/chromedp v0.8.1
..\..\..\..\go\pkg\mod\github.com\chromedp\chromedp@v0.8.1\emulate.go:5:2: found packages device (device.go) and main (gen.go) in C:\Users\Yaseen\go\pkg\mod\github.com\chromedp\chromedp@v0.8.1\device
..\..\..\..\go\pkg\mod\github.com\chromedp\chromedp@v0.8.1\input.go:9:2: import "github.com/chromedp/chromedp/kb" is a program, not an importable package

**Comment by RodricBr** [comment]
Try running:
- `go mod init airixss.go`

and then

- `go mod tidy`

Then you should have an executable ready to use
