### ISSUE TITLE
Running airix local files html

### ISSUE THREAD

**Issue by Marcio861** [ferreiraklet/airixss#6]
Is possible airixss running  peer example echo "file:///home/file.html"  | airixss -p "confirm(1)" ?

**Comment by ferreiraklet** [comment]
Oh hey Marcio
No, you cant use the file:// wrapper,
However, what you can do is start a simple server, or apache server, and do whatever you want
Example: use apache2
Example: use python3 -m http.server port

**Comment by Marcio861** [comment]
thankyou
